# Generated by Django 4.0.6 on 2023-07-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city_address', models.CharField(max_length=100)),
                ('tax_rate', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('total', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('price_per_lbs', models.FloatField()),
                ('weight', models.FloatField()),
                ('amount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.invoice')),
            ],
        ),
    ]
