# Generated by Django 4.0.5 on 2023-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_invoice_discount_rate_alter_invoice_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
