# Generated by Django 4.0.6 on 2023-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_invoice_discount_rate_alter_invoice_tax_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city_address', models.CharField(max_length=100)),
            ],
        ),
    ]
