# Generated by Django 4.0.6 on 2023-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.TextField(default='My Comments'),
            preserve_default=False,
        ),
    ]
